#!/bin/bash
# scripts/compile_sage_shell.sh
#
# Compiles the SageLang shell sources into a single bytecode blob and
# emits it as a C header: kernel/shell/sage_shell_bytecode.h
#
# Usage: bash scripts/compile_sage_shell.sh [/path/to/sage] [output_dir]
#
# The `sage` interpreter must be on PATH or passed as first argument.
# The three .sage sources are concatenated (input.sage + commands.sage +
# shell.sage) so they share a single bytecode chunk, which is what
# MetalVM expects via metal_vm_load().

set -euo pipefail

SAGE="${1:-sage}"
OUT_DIR="${2:-kernel/shell}"
OUT_H="${OUT_DIR}/sage_shell_bytecode.h"

SAGE_SHELL_DIR="kernel/shell/sage_shell"
INPUT="${SAGE_SHELL_DIR}/input.sage"
COMMANDS="${SAGE_SHELL_DIR}/commands.sage"
SHELL_MAIN="${SAGE_SHELL_DIR}/shell.sage"
COMBINED="/tmp/sage_shell_combined.sage"
BYTECODE="/tmp/sage_shell.bin"

echo "[sage-shell] Combining .sage sources..."
cat "${INPUT}" "${COMMANDS}" "${SHELL_MAIN}" > "${COMBINED}"

echo "[sage-shell] Compiling to bytecode..."
# sage --compile-bytecode outputs a raw binary bytecode file
"${SAGE}" --compile-bytecode "${COMBINED}" -o "${BYTECODE}"

echo "[sage-shell] Generating C header: ${OUT_H}..."
python3 - "${BYTECODE}" "${OUT_H}" <<'PYEOF'
import sys, os

src  = sys.argv[1]
dest = sys.argv[2]

with open(src, "rb") as f:
    data = f.read()

size = len(data)
lines = []
lines.append("/* Auto-generated by scripts/compile_sage_shell.sh — DO NOT EDIT */")
lines.append("#pragma once")
lines.append("#include <stdint.h>")
lines.append(f"static const uint8_t sage_shell_bytecode[] = {{")

ROW = 16
for i in range(0, size, ROW):
    chunk = data[i:i+ROW]
    hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
    lines.append(f"    {hex_str},")

lines.append("};")
lines.append(f"static const int sage_shell_bytecode_len = {size};")

with open(dest, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"[sage-shell] Wrote {size} bytes -> {dest}")
PYEOF

echo "[sage-shell] Done. Bytecode header ready at ${OUT_H}"
